### PR TITLE
Initial MPI support

### PR DESCRIPTION
**Pull request by carstenbauer**
See #51

### CODE REVIEW

**Comment by carstenbauer** [comment]
```julia
#!/usr/bin/env sh
#SBATCH -N 1
#SBATCH -n 2
#SBATCH --cpus-per-task=5
#SBATCH --ntasks-per-socket=1
#SBATCH -o sl_%j.out
#SBATCH -A pc2-mitarbeiter
#SBATCH -p all
#SBATCH -t 00:02:00
#=
srun julia --project -t 5 $(scontrol show job $SLURM_JOBID | awk -F= '/Command=/{print $2}')
exit
# =#
using MPI
using ThreadPinning

MPI.Init()

rank = MPI.Comm_rank(MPI.COMM_WORLD)

pinthreads(:affinitymask)

sleep(0.3 * rank)
println("Rank $rank: ", getcpuids())

MPI.Finalize()
```

gives

```
Rank 0: [0, 1, 2, 3, 4]
Rank 1: [64, 65, 66, 67, 68]
```

on Noctua 2 (dual-socket system with 64 cores per socket).

**Comment by giordano** [comment]
Seems to be working as expected. On AMD EPYC 7742 (2 x 64 cores, without multithreading):
```
> srun -n 32 --distribution=block:block --hint=nomultithread julia -t 4 --color=yes pinning.jl
Rank 0: [0, 1, 2, 3]
Rank 1: [4, 5, 6, 7]
Rank 2: [8, 9, 10, 11]
Rank 3: [12, 13, 14, 15]
Rank 4: [16, 17, 18, 19]
Rank 5: [20, 21, 22, 23]
Rank 6: [24, 25, 26, 27]
Rank 7: [28, 29, 30, 31]
Rank 8: [32, 33, 34, 35]
Rank 9: [36, 37, 38, 39]
Rank 10: [40, 41, 42, 43]
Rank 11: [44, 45, 46, 47]
Rank 12: [48, 49, 50, 51]
Rank 13: [52, 53, 54, 55]
Rank 14: [56, 57, 58, 59]
Rank 15: [60, 61, 62, 63]
Rank 16: [64, 65, 66, 67]
Rank 17: [68, 69, 70, 71]
Rank 18: [72, 73, 74, 75]
Rank 19: [76, 77, 78, 79]
Rank 20: [80, 81, 82, 83]
Rank 21: [84, 85, 86, 87]
Rank 22: [88, 89, 90, 91]
Rank 23: [92, 93, 94, 95]
Rank 24: [96, 97, 98, 99]
Rank 25: [100, 101, 102, 103]
Rank 26: [104, 105, 106, 107]
Rank 27: [108, 109, 110, 111]
Rank 28: [112, 113, 114, 115]
Rank 29: [116, 117, 118, 119]
Rank 30: [120, 121, 122, 123]
Rank 31: [124, 125, 126, 127]
```
Each rank has threads neatly grouped.  Thanks!

**Comment by giordano** [comment]
BTW, I just realised that thanks to https://github.com/JuliaLang/julia/pull/42340, in Julia v1.9 this package is unnecessary.  Without any pinning at all:
```console
> srun -n 32 --distribution=block:block --hint=nomultithread julia -t auto --color=yes pinning.jlRank 0: [1, 2, 3, 0]
Rank 1: [5, 7, 4, 6]
Rank 2: [8, 9, 11, 10]
Rank 3: [13, 14, 15, 12]
Rank 4: [19, 17, 16, 18]
Rank 5: [20, 21, 23, 22]
Rank 6: [26, 27, 24, 25]
Rank 7: [29, 30, 31, 28]
Rank 8: [34, 33, 35, 32]
Rank 9: [36, 38, 39, 37]
Rank 10: [43, 40, 41, 42]
Rank 11: [44, 45, 47, 46]
Rank 12: [51, 48, 49, 50]
Rank 13: [54, 52, 55, 53]
Rank 14: [57, 58, 59, 56]
Rank 15: [60, 62, 61, 63]
Rank 16: [64, 66, 65, 67]
Rank 17: [68, 70, 69, 71]
Rank 18: [73, 74, 75, 72]
Rank 19: [77, 76, 78, 79]
Rank 20: [80, 81, 82, 83]
Rank 21: [85, 84, 86, 87]
Rank 22: [89, 88, 90, 91]
Rank 23: [92, 94, 93, 95]
Rank 24: [99, 96, 98, 97]
Rank 25: [101, 102, 103, 100]
Rank 26: [104, 106, 105, 107]
Rank 27: [111, 108, 110, 109]
Rank 28: [115, 113, 112, 114]
Rank 29: [118, 117, 119, 116]
Rank 30: [121, 120, 123, 122]
Rank 31: [125, 127, 124, 126]
```

But this package is certainly still useful for better manual control of threads pinning, and anyway for older versions of Julia.

**Comment by carstenbauer** [comment]
Added a function `pinthreads_mpi` that allows one to explicitly pin MPI ranks (for a single node) to specific domains (currently, sockets or memory domains).

Example without external pinning (SLURM doesn't set a restricted affinity mask in this case).

```julia
#!/usr/bin/env sh
#SBATCH -N 1
#SBATCH -o sl_%j.out
#SBATCH -A pc2-mitarbeiter
#SBATCH -p all
#SBATCH -t 00:02:00
#=
srun -n 4 julia --project -t 10 $(scontrol show job $SLURM_JOBID | awk -F= '/Command=/{print $2}')
exit
# =#
using MPI
using ThreadPinning

MPI.Init()

nranks = MPI.Comm_size(MPI.COMM_WORLD)
rank = MPI.Comm_rank(MPI.COMM_WORLD)

pinthreads_mpi(:sockets, rank, nranks)

sleep(0.3 * rank)
println("Rank $rank: ", getcpuids())

MPI.Finalize()
```

gives

```
Rank 0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Rank 1: [64, 65, 66, 67, 68, 69, 70, 71, 72, 73]
Rank 2: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Rank 3: [74, 75, 76, 77, 78, 79, 80, 81, 82, 83]
```

**Comment by carstenbauer** [comment]
> BTW, I just realised that thanks to [JuliaLang/julia#42340](https://github.com/JuliaLang/julia/pull/42340), in Julia v1.9 this package is unnecessary. Without any pinning at all:
> 
> But this package is certainly still useful for better manual control of threads pinning, and anyway for older versions of Julia.

Yes, that is a great improvement (that I'm aware of)! But it "only" covers cases where the affinity mask is set externally, for example via `taskset` (PR) or SLURM (your example) which, BTW, might also effect non-"Julia user threads" (e.g. OpenBLAS pthreads etc.). So, "this package is unnecessary" and "without any pinning at all" isn't correct, you're just using SLURM for pinning.

Some points for TP.jl (beyond what you've already mentioned):

* TP.jl also lets you pin your Julia threads if you aren't using SLURM.
* TP.jl lets you pin threads *dynamically* from inside a Julia session. This is great for interactivity, tutorials etc. (in particular in Jupyter and or Pluto) but also for libraries like LIKWID.jl that want to dynamically take care of the pinning for the user (telling him/her to restart Julia under `taskset` or similar would be pretty annoying).
* TP.jl has `threadinfo` to nicely show you what you're doing and what the system looks like (need to think about how to generalize this to MPI cases).
* TP.jl gives you *logical indexing*: you can readily pin to, say, the second SMT-thread in the fifth core in the first socket without having to care about what the "physical" id of that CPU-thread is.
* From Julia 1.9 on, TP.jl allows you to explicitly pin the OpenBLAS threads as well (beta).

**Comment by carstenbauer** [comment]
@giordano 

```
$ cat getcpuids_all.jl 
using ThreadPinning
ThreadPinning.openblas_print_affinity_masks() # requires Julia >= 1.9
println(getcpuids())

$ OPENBLAS_NUM_THREADS=10 taskset --cpu-list 0-9 julia +1.9 --project -t 10 getcpuids_all.jl
Julia threadid: 1
1:   |11111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000|
2:   |11111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000|
3:   |11111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000|
4:   |11111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000|
5:   |11111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000|
6:   |11111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000|
7:   |11111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000|
8:   |11111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000|
9:   |11111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000|
10:  |11111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000|

[1, 7, 8, 2, 3, 0, 6, 4, 4, 7]
```

As you can see, the affinity mask is restricting the Julia threads to the correct set of CPUs but it does not ensure that Julia threads run on different CPUs. I would expect the same thing to be true for SLURM, so you probably were somewhat "lucky" above (try increasing the number of threads per rank and/or rerunning the same thing multiple times). (OpenBLAS threads obviously also respect the mask.)

**Comment by carstenbauer** [comment]
TODO (for self)
* [ ] Add MPI section to the docs
  * [ ] Basic direct example
  * [ ] SLURM example
* [ ] Add external affinity mask tests more systematically
  * [ ] taskset
  * [ ] numactl
  * [ ] Julia 1.9

**Comment by giordano** [comment]
> So, "without any pinning at all" isn't correct, you're just using SLURM for pinning.

I meant to say "without using `pinthreads` at all in my script", of course I was relying on external pinning.

>  so you probably were somewhat "lucky" above (try increasing the number of threads per rank and/or rerunning the same thing multiple times)

Not sure that was just luck.  I did run the same code multiple times before posting the result, and threads were always pinned as I've shown above (as you can see, within each MPI rank the "order" of the thread is different than with `pinthreads(:affinitymask)`, but the thread pool is the same).

Note that contrary to your examples I used `srun ... --distribution=block:block --hint=nomultithread julia --threads auto ...`, which is what I was recommended to do by the sysadmin.  For example without `--hint=nomultithread` some hyperthreading threads would be used, without `--distribution` threads would be spread seemingly randomly (probably there was a pattern but I didn't bother understanding it).

To be clear, in any case I'm really looking forward to `pinthreads(:affinitymask)` because we're probably going to use Julia v1.8 (so can't use `--threads auto` anyway) and as I think this is in general still useful to better control threads pinning than relying on whatever `--threads auto` does, I didn't want to disparage your work!

**Comment by carstenbauer** [comment]
> I didn't want to disparage your work!

Although my lengthy replies might have suggested otherwise, I didn't take it that way at all :) It's more that I took this as a reason to analyse in more detail what Julia >= 1.9 is doing and what the selling points of ThreadPinning.jl are after 1.9 is out.

> Not sure that was just luck. I did run the same code multiple times before posting the result, and threads were always pinned as I've shown above (as you can see, within each MPI rank the "order" of the thread is different than with `pinthreads(:affinitymask)`, but the thread pool is the same).

Just to be clear, by "luck" I didn't mean that it's entirely random. The OS scheduler will (hopefully) be smarter than to put all threads on the same CPU-core (and it apparently was in your particular case). What I meant is that you can't rely on threads running on different CPU-cores within the mask (and certainly not the order). It's the same as when you start Julia without any particular affinity mask: Julia threads will typically not run on the same CPU-core but they can (and sometimes do).

Also note that it's not surprising at all that the "thread pool is the same", i.e. that threads run on CPU-cores within the not-masked-out domain, since that's precisely what the (process) affinity mask is good for.

> Note that contrary to your examples I used `srun ... --distribution=block:block --hint=nomultithread julia --threads auto ...`, which is what I was recommended to do by the sysadmin. For example without `--hint=nomultithread` some hyperthreading threads would be used, without `--distribution` threads would be spread seemingly randomly (probably there was a pattern but I didn't bother understanding it).

Although I'm not 100% certain, it's very unlikely that SLURM is doing more than just setting the process affinity mask (like all other generic tools) (*). And that just means that threads are **not** fixed to individual, non-overlapping CPU-threads but only ranges. If I find the time, I'll try to use the same settings as you and prove it to you :) But you can also do it yourself by
1) comparing the `ThreadPinning.print_affinity_masks()` output of your variant and an explicit `pinthreads(:affinitymask)`
2) using less ranks but more threads per rank and repeating the experiment multiple times (I had to try it about 10 times to see an overlap).

(*) Mostly because that it is pretty tricky and involves overloading/patching (`LD_PRELOAD`) `pthread` or whatever threading library is used (at least that's what `likwid-pin` does, which similar to `pinthreads(:affinitymask)` tries to pin each thread individually, i.e. to set the thread affinity and not just the process affinity).

**Comment by carstenbauer** [comment]
@giordano I ran the same experiment as you (Julia 1.9). While I was right, that SLURM doesn't set the thread affinity to individual CPU-threads (see the affinity masks below), Julia threads nonetheless appeared to be running on separate CPU-threads in my 10 test runs. Again, conceptually, this tells me that I can't rely on this to be the case but it is indeed surprising that it is so robust. Maybe there is some other mechanism at place that I'm not aware about? But until someone can clarify this, I still wouldn't rely on it.

```
cpu-bind=MASK - cn-0131, task  0  0 [525152]: mask |BBBBBBBBBBBBBBBBBBBB||||BBBBBBBBBBBBBBBBBBBB|  set
[33, 35, 37, 38, 32, 39, 30, 34, 31, 36]
[3, 4, 6, 7, 8, 9, 0, 1, 2, 5]
[29, 25, 27, 28, 20, 22, 21, 23, 24, 26]
[19, 15, 12, 14, 11, 13, 18, 17, 10, 16]
true
true
true
true




1:   |00000000000000000000|00000000001111111111|
2:   |00000000000000000000|00000000001111111111|
3:   |00000000000000000000|00000000001111111111|
4:   |00000000000000000000|00000000001111111111|
5:   |00000000000000000000|00000000001111111111|
6:   |00000000000000000000|00000000001111111111|
7:   |00000000000000000000|00000000001111111111|
8:   |00000000000000000000|00000000001111111111|
9:   |00000000000000000000|00000000001111111111|
10:  |00000000000000000000|00000000001111111111|
1:   |11111111110000000000|00000000000000000000|
2:   |11111111110000000000|00000000000000000000|
3:   |11111111110000000000|00000000000000000000|
4:   |11111111110000000000|00000000000000000000|
5:   |11111111110000000000|00000000000000000000|
6:   |11111111110000000000|00000000000000000000|
7:   |11111111110000000000|00000000000000000000|
8:   |11111111110000000000|00000000000000000000|
9:   |11111111110000000000|00000000000000000000|
10:  |11111111110000000000|00000000000000000000|
1:   |00000000000000000000|11111111110000000000|
2:   |00000000000000000000|11111111110000000000|
3:   |00000000000000000000|11111111110000000000|
4:   |00000000000000000000|11111111110000000000|
5:   |00000000000000000000|11111111110000000000|
6:   |00000000000000000000|11111111110000000000|
7:   |00000000000000000000|11111111110000000000|
8:   |00000000000000000000|11111111110000000000|
9:   |00000000000000000000|11111111110000000000|
10:  |00000000000000000000|11111111110000000000|
1:   |00000000001111111111|00000000000000000000|
2:   |00000000001111111111|00000000000000000000|
3:   |00000000001111111111|00000000000000000000|
4:   |00000000001111111111|00000000000000000000|
5:   |00000000001111111111|00000000000000000000|
6:   |00000000001111111111|00000000000000000000|
7:   |00000000001111111111|00000000000000000000|
8:   |00000000001111111111|00000000000000000000|
9:   |00000000001111111111|00000000000000000000|
10:  |00000000001111111111|00000000000000000000|
```

**Pull request merged**
